debug: false
options:
  support-essentialsx-chat: false
  #With this enabled, you can add the "{TAG}" placeholder in the essentialsX Chat configuration and it will be replaced with the current tag of the player
  default-tag:
    enabled: false
    #Should we use a "default tag" if the player has none ?
    tag: default
    #Which tag should we use if the player has none ? ("default-tag.enabled" has to be true)

storage:
  #Default mode is SQLlite, Mode Available: SQLlite, MySQL.
  mode: SQLlite
  mysql-credentials:
    host: your-host
    port: your-port
    database: your-database
    username: your-username
    password: your-password

    #Options
    useSSL: false

GUI:
  title: "&7Main menu"
  total-slots: 54
  total-pages: 2 #(Minimum 1)

  #Here are the main item in the gui, you can all disabled them by switching "enabled" to false.
  items:
    #This item will be placed in every empty slot in the GUI. If you want nothing in it, put "enabled" to false
    empty-slots:
      enabled: true
      display: "&8"
      material: black_stained_glass_pane
      lore: [ ]
    #This item will be placed at the slot of any tags the player don't have the permission to use.
    #You can use %tag%, %tag-id% placeholders in the name & lore.
    change-item:
      enabled: false
      display: "&c&lACCESS REFUSED &8- %tag%"
      material: head-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDE5MjZiZmE5Y2FmOGJjYTkwNjkyNzgwOTc4YjVjNzRkNzEzZTg2NWY1YmRkMzc5MjA5N2IxODc5OTk3ZTU1NyJ9fX0=
      lore: [ ]
    next-page:
      enabled: true
      slot: 53
      display: "&7Click here to go to the next page"
      material: head-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDllY2NjNWMxYzc5YWE3ODI2YTE1YTdmNWYxMmZiNDAzMjgxNTdjNTI0MjE2NGJhMmFlZjQ3ZTVkZTlhNWNmYyJ9fX0=
      lore: [ ]
    previous-page:
      enabled: true
      slot: 45
      display: "&7Click here to go to the previous page"
      material: head-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODY0Zjc3OWE4ZTNmZmEyMzExNDNmYTY5Yjk2YjE0ZWUzNWMxNmQ2NjllMTljNzVmZDFhN2RhNGJmMzA2YyJ9fX0=
      lore: [ ]

  #Here are custom items, you can create and add as many items as you want in the GUI !
  #Support placeholders from PlaceholderAPI in name and lore.
  custom-items:
    player_information:
      enabled: true
      slot: 0
      material: head-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjcwNWZkOTRhMGM0MzE5MjdmYjRlNjM5YjBmY2ZiNDk3MTdlNDEyMjg1YTAyYjQzOWUwMTEyZGEyMmIyZTJlYyJ9fX0=
      name: "&7Your current tag: %robottags_player%"
      lore: []
      right-click: [ ]
      left-click: [ ]
    clear_tag:
      enabled: true
      slot: 8
      material: head-eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2VkMWFiYTczZjYzOWY0YmM0MmJkNDgxOTZjNzE1MTk3YmUyNzEyYzNiOTYyYzk3ZWJmOWU5ZWQ4ZWZhMDI1In19fQ==
      name: "&7Click here to remove your tag"
      lore: []
      right-click:
        - "[CONSOLE] robottags clear %player%"
        - "[MESSAGE]%prefix% &7Your tag has been removed."
        - "[CLOSE]"
      left-click:
        - "[CONSOLE] robottags clear %player%"
        - "[MESSAGE]%prefix% &7Your tag has been removed."
        - "[CLOSE]"
    close-gui:
      enabled: true
      slot: 49
      name: "&cClose the inventory"
      material: barrier
      lore: []
      right-click:
        - "[CLOSE]"
      left-click:
        - "[CLOSE]"